# Data Structure in Pandas

In [1]:
# There are two type of data structure in pandas first is 
# 1. Series 
# 2. DataFrame

# Series

In [2]:
import pandas as pd

In [9]:
import pandas as pd
x = [3,4,5,6,7]
var = pd.Series(x)
print(var)

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [8]:
# agar mujy index ko khud badlna ho or khud koi or value dani ho index ki jagha

In [10]:
var = pd.Series(x, index = ['m','a','j','i','d'])
print(var)

m    3
a    4
j    5
i    6
d    7
dtype: int64

In [11]:
# hum list k ilava dictionary b use kar sakty hai

In [15]:
dic = {"name":['Majid','Abu_Bakar','Dildar','Usman'],"roll_number":[121250,121251,121252,121253,12124],"Age":[22,34,54,32,43]}
y = pd.Series(dic)
print(y)

name                 [Majid, Abu_Bakar, Dildar, Usman]
roll_number    [121250, 121251, 121252, 121253, 12124]
Age                               [22, 34, 54, 32, 43]
dtype: object

In [16]:
# No broadcast error in pandas Series

In [17]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([1,2,3,4])
print(s1+s2)

0    2.0
1    4.0
2    6.0
3    8.0
4    NaN
dtype: float64

# DataFrame in Pandas

In [20]:
a = [1,2,3,4,5,6,7,8,9,10]
b = pd.DataFrame(a)
print(b)

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [26]:
dic1 = {
    "name":['python','c++','java','react','node.js','angular','veu'],
    "teacher":['Maryam',"Waheed","Bisma","Zahra","Binish","Bilal","shoaib"],
    "center":['hafizabad','fasilabad','lahore','islamabad','karachi','pashavar','dara_ghazi_khan']
}
n = pd.DataFrame(dic1)
print(n)

      name teacher           center
0   python  Maryam        hafizabad
1      c++  Waheed        fasilabad
2     java   Bisma           lahore
3    react   Zahra        islamabad
4  node.js  Binish          karachi
5  angular   Bilal         pashavar
6      veu  shoaib  dara_ghazi_khan

In [28]:
xy = pd.DataFrame([[1,2,3],[1,2,3]])
print(xy)

   0  1  2
0  1  2  3
1  1  2  3

# Arithmetic Operation in Pandas

In [4]:
import pandas as pd
a = pd.DataFrame([1,2,3,4,5])
b = pd.DataFrame([1,2,3,4,5])
print(a+b)

    0
0   2
1   4
2   6
3   8
4  10

In [13]:
x= pd.DataFrame({
    "A":[1,2,3,4,5],"B":["Majid","Ali","Abu_Bakar","Abu_Huraira","Ahmad Raza"],"C":[3.09, 2.24,2.46,3.04,2.85]
    
})
y =pd.DataFrame({
    "A":[1,2,3,4,5],"B":["majid","ali","abu_bakar","abu_huraira","ahmad raza"],"C":[3.09,2.24,2.46,3.04,2.85]
})
# print(x+y)
# print(x)
x["C"]>3
print(x)

   A            B     C
0  1        Majid  3.09
1  2          Ali  2.24
2  3    Abu_Bakar  2.46
3  4  Abu_Huraira  3.04
4  5   Ahmad Raza  2.85

# How to delete and insert data

In [22]:
#Insert
var = pd.DataFrame({
    "A":[1,2,3,4,5],
    "B":[9,8,7,6,5],
    "C":["M","A","J","I","D"]
})
var.insert(1,"python",var["A"])
var

   A  python  B  C
0  1       1  9  M
1  2       2  8  A
2  3       3  7  J
3  4       4  6  I
4  5       5  5  D

In [23]:
var.insert(2,"Majid",var["C"])
var

   A  python Majid  B  C
0  1       1     M  9  M
1  2       2     A  8  A
2  3       3     J  7  J
3  4       4     I  6  I
4  5       5     D  5  D

In [31]:
# Delete
var1 = pd.DataFrame({
    "Majid":["M","A","J","I","D"],
    "Ahmad":["A","H","M","A","D"],
    "Awais":["A","W","A","I","S"]
})
var1.insert(1,"python",[11,12,13,14,15])
var1.pop("Awais")
print(var1)

  Majid  python Ahmad
0     M      11     A
1     A      12     H
2     J      13     M
3     I      14     A
4     D      15     D